language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - "12"
git:
  depth: 4
script:
  - yarn build
deploy:
  provider: firebase
  skip-cleanup: true
  keep-history: true
  token: $FIREBASE_CI
  project: "alejozepol-4d4f3"
  local-dir: ./dist
  target-branch: master
  commit_message: "deploy del proyecto"
  on:
    branch: master
